//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace u22559711_HW03.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class LibraryEntities1 : DbContext
    {
        public LibraryEntities1()
            : base("name=LibraryEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<authors> authors { get; set; }
        public virtual DbSet<books> books { get; set; }
        public virtual DbSet<borrows> borrows { get; set; }
        public virtual DbSet<students> students { get; set; }
        public virtual DbSet<types> types { get; set; }
    
        public virtual ObjectResult<MostBorrowedBooks_Result> MostBorrowedBooks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostBorrowedBooks_Result>("MostBorrowedBooks");
        }
    
        public virtual ObjectResult<MostBorrowedBooksDecide_Result> MostBorrowedBooksDecide(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MostBorrowedBooksDecide_Result>("MostBorrowedBooksDecide", startDateParameter, endDateParameter);
        }
    }
}
